/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CpuChart: typeof import('./src/components/CpuChart/index.vue')['default']
    CpuConfig: typeof import('./src/components/MenuConfig/CpuConfig/index.vue')['default']
    FilePathPrompt: typeof import('./src/components/PromptModel/FilePathPrompt.vue')['default']
    IconContentLayout: typeof import('./src/components/IconContentLayout/index.vue')['default']
    MemoryChart: typeof import('./src/components/MemoryChart/index.vue')['default']
    MonkeyConfig: typeof import('./src/components/MenuConfig/MonkeyConfig.vue')['default']
    ProcessChart: typeof import('./src/components/ProcessChart/index.vue')['default']
    ProcessMemChart: typeof import('./src/components/ProcessMemChart/index.vue')['default']
    PromptModel: typeof import('./src/components/PromptModel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiConfig: typeof import('./src/components/MenuConfig/UiConfig.vue')['default']
    VersionConfig: typeof import('./src/components/MenuConfig/VersionConfig.vue')['default']
  }
}
