/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ABotton: typeof import('@arco-design/web-vue')['Botton']
    CpuChart: typeof import('./src/components/CpuChart.vue')['default']
    CpuChats: typeof import('./src/components/CpuChats.vue')['default']
    CPUchats: typeof import('./src/components/CPUchats.vue')['default']
    CpuConfig: typeof import('./src/components/CpuConfig.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MonkeyConfig: typeof import('./src/components/MonkeyConfig.vue')['default']
    MonkeyOption: typeof import('./src/components/MonkeyOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
