/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CpuChart: typeof import('./src/components/CpuChart.vue')['default']
    CpuChat: typeof import('./src/components/CpuChart/index.vue')['default']
    CpuConfig: typeof import('./src/components/MenuConfig/CpuConfig.vue')['default']
    IconContentLayout: typeof import('./src/components/IconContentLayout/index.vue')['default']
    IconLayout: typeof import('./src/components/IconLayout/index.vue')['default']
    MonkeyConfig: typeof import('./src/components/MenuConfig/MonkeyConfig.vue')['default']
    MonkeyOption: typeof import('./src/components/MonkeyOption.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
